#!/usr/bin/env python3

import csv
import sys
from datetime import datetime
import qifparse.qif as qif

# Usage: dkb2qif infile outfile

input_path = sys.argv[1]
output_path = sys.argv[2]

def parse_row(row):
   date = datetime.strptime(row[0], '%d.%m.%Y')
   if row[3]:
      payee = '{} - {}'.format(row[3], row[4])
   else:
      payee = row[4]
   memo = row[2]
   amount = float(row[7].replace('.', '').replace(',', '.'))

   return qif.Transaction(date=date, amount=amount, payee=payee, memo=memo)

with open(input_path, 'r', encoding='iso-8859-1') as infile:
   csv_reader = csv.reader(infile, delimiter=';', quotechar='"')
   qif_obj = qif.Qif()
   row = next(csv_reader)
   acc = qif.Account(name=row[1], account_type='Bank')
   qif_obj.add_account(acc)
   for row in csv_reader:
      if len(row) == 12 and row[0] != 'Buchungstag':
         transaction = parse_row(row)
         acc.add_transaction(transaction, header='!Type:Bank')
   with open(output_path, mode='w') as outfile:
      outfile.write(str(qif_obj))

